/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 */

plugins {
    id("java")
}

subprojects {
    apply(plugin = "java")

    group = "me.dwywdo.labs.java"
    version = "1.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }

    dependencies {
        /**
         * JUnit5 = JUnit Platform + JUnit Jupiter (JUnit5) + JUnit Vintage (TestEngine for JUnit3/4)
         * Ref. https://docs.gradle.org/current/userguide/java_testing.html#using_junit5
         */
        testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")

        /**
         * If you want to run JUnit 3/4 tests on JUnit Platform, or even mix them with Jupiter tests, you should add extra JUnit Vintage Engine dependencies
         * Ref. https://docs.gradle.org/current/userguide/java_testing.html#executing_legacy_tests_with_junit_vintage
         */
        // testCompileOnly("junit:junit:4.13")
        // testRuntimeOnly("org.junit.vintage:junit-vintage-engine")
    }

    tasks.getByName<Test>("test") {
        useJUnitPlatform()
    }
}




