rootProject.name = "java-lab"
include("collection-api")
include("effective-java")
include("concurrency-api")
include("time-date-api")
include("java-in-action")
include("interface")
include("java-io:basic")
include("java-io:echo")
include("gof-design-patterns")
include("gof-design-patterns:creational:sample")
include("gof-design-patterns:creational:abstract-factory")
include("gof-design-patterns:structural:adapter")
