/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.dwywdo.lab.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.file.RegularFile
import org.gradle.testing.jacoco.plugins.JacocoPlugin
import org.gradle.testing.jacoco.tasks.JacocoCoverageVerification
import org.gradle.testing.jacoco.tasks.JacocoReport

/**
 * Coverage Lock In Plugin that locks in test coverage gain in a text file
 */
class CoverageLockPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("coverageLockIn", CoverageLockInExtension::class.java)

        initializeExtension(project, extension)

        project.plugins.apply(JacocoPlugin::class.java)

        configureJacoco(project, extension)
    }

    private fun initializeExtension(project: Project, extension: CoverageLockInExtension) = extension.apply {
        this.coverageFile.convention(project.layout.projectDirectory.file("coverage_lock_in.txt") as RegularFile)
        this.goal.convention(0.8f)
        this.counter.convention("LINE")
        this.onCi.convention(false)
        this.internalCurrentCoverage.convention(
            project.providers.fileContents(extension.coverageFile).asText.map { it.toFloat() }.orElse(extension.goal)
        )
        this.internalCurrentCoverage.disallowChanges()
    }

    /**
     * Configures the Jacoco tasks.
     */
    private fun configureJacoco(project: Project, extension: CoverageLockInExtension) {
        project.tasks.named("jacocoTestReport", JacocoReport::class.java) { task ->
            task.dependsOn("test")
            task.reports.xml.required.set(true)
            task.finalizedBy("jacocoTestCoverageVerification")
        }

        project.tasks.named("jacocoTestCoverageVerification", JacocoCoverageVerification::class.java) { task ->
            task.dependsOn("jacocoTestReport")

            task.violationRules.rule { rule ->
                rule.limit { limit ->
                    limit.counter = extension.counter.get()
                    limit.value = "COVEREDRATIO"
                    limit.minimum = extension.internalCurrentCoverage.get().toBigDecimal()
                }
            }
        }
    }
}

