dwywdo:
  greeter:
    userName: dwywdo
    morningMessage: Good morning, dwywdo!
    afternoonMessage: Good afternoon, dwywdo!
    eveningMessage: Good evening, dwywdo!
    nightMessage: Good night, dwywdo!

