say-hello: Hello World!
color-list: red, blue, green, white, black
configs: "{\
         key1: \"ANY String Value here\", \
         key2: \"any number of items\" , \
         key3: \"Note the Last item does not have comma\" \
         }"

app:
    name: dwywdo blog
    description: this is dwywdo's blog
    url: https://dwywdo.github.io
    user:
        username: admin
        password: password
        roles: ADMIN, USER

dwywdo:
  greeter:
    userName: dwywdo
    morningMessage: Good morning, dwywdo!
    afternoonMessage: Good afternoon, dwywdo!
    eveningMessage: Good evening, dwywdo!
    nightMessage: Good night, dwywdo!
