spring:
  main:
    web-application-type: none

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - beans
          - prometheus

armeria:
  ports:
    - port: 20080
      protocols:
        - http
  health-check-path: /healthcheck
