/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.dwywdo.lab.gradle

import org.gradle.testkit.runner.BuildResult
import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder

/**
 * A simple functional test for the 'me.dwywdo.lab.gradle.coveragelock' plugin.
 */
class CoverageLockPluginFunctionalTest {

    @get:Rule
    val tempFolder = TemporaryFolder()

    @Test
    fun `no coverage file`() {
        setupTestProject("just_plugin_applied")
        val log: String = runAndGetLogs(false, "jacocoTestReport");
        assertTrue(log.contains("but expected minimum is 0.8"))
    }

    @Test fun `with coverage file`() {
        setupTestProject("just_plugin_with_file")
        val log : String = runAndGetLogs(false, "jacocoTestReport");
        assertTrue(log.contains("but expected minimum is 0.6"))
    }

    private fun runAndGetLogs(expectSuccess: Boolean, taskToRun: String): String {
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withProjectDir(tempFolder.root)
        runner.withArguments(taskToRun)
        val result: BuildResult = if (expectSuccess) runner.build() else runner.buildAndFail()

        return result.output
    }

    private fun setupTestProject(dir: String) {
        val srcDir = File("src/functionalTest/resources", dir)
        srcDir.copyRecursively(tempFolder.root)
    }
}
