/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.dwywdo.lab.gradle

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'me.dwywdo.lab.gradle.coveragelock' plugin.
 */
class CoverageLockPluginTest {
    @Test fun `plugin creates extension`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("application")
        project.plugins.apply("me.dwywdo.lab.gradle.coveragelock")

        println(project.extensions)
    }
}
